// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: api/consumer/service/v1/consumer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateConsumerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateConsumerReq) Reset() {
	*x = CreateConsumerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateConsumerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConsumerReq) ProtoMessage() {}

func (x *CreateConsumerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConsumerReq.ProtoReflect.Descriptor instead.
func (*CreateConsumerReq) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{0}
}

type CreateConsumerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateConsumerReply) Reset() {
	*x = CreateConsumerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateConsumerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConsumerReply) ProtoMessage() {}

func (x *CreateConsumerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConsumerReply.ProtoReflect.Descriptor instead.
func (*CreateConsumerReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{1}
}

type UpdateConsumerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateConsumerReq) Reset() {
	*x = UpdateConsumerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConsumerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConsumerReq) ProtoMessage() {}

func (x *UpdateConsumerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConsumerReq.ProtoReflect.Descriptor instead.
func (*UpdateConsumerReq) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{2}
}

type UpdateConsumerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateConsumerReply) Reset() {
	*x = UpdateConsumerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConsumerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConsumerReply) ProtoMessage() {}

func (x *UpdateConsumerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConsumerReply.ProtoReflect.Descriptor instead.
func (*UpdateConsumerReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{3}
}

type DeleteConsumerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteConsumerReq) Reset() {
	*x = DeleteConsumerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteConsumerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConsumerReq) ProtoMessage() {}

func (x *DeleteConsumerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConsumerReq.ProtoReflect.Descriptor instead.
func (*DeleteConsumerReq) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{4}
}

type DeleteConsumerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteConsumerReply) Reset() {
	*x = DeleteConsumerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteConsumerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConsumerReply) ProtoMessage() {}

func (x *DeleteConsumerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConsumerReply.ProtoReflect.Descriptor instead.
func (*DeleteConsumerReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{5}
}

type GetConsumerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConsumerReq) Reset() {
	*x = GetConsumerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerReq) ProtoMessage() {}

func (x *GetConsumerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerReq.ProtoReflect.Descriptor instead.
func (*GetConsumerReq) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{6}
}

type GetConsumerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConsumerReply) Reset() {
	*x = GetConsumerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerReply) ProtoMessage() {}

func (x *GetConsumerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerReply.ProtoReflect.Descriptor instead.
func (*GetConsumerReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{7}
}

type ListConsumerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListConsumerReq) Reset() {
	*x = ListConsumerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConsumerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumerReq) ProtoMessage() {}

func (x *ListConsumerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumerReq.ProtoReflect.Descriptor instead.
func (*ListConsumerReq) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{8}
}

type ListConsumerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListConsumerReply) Reset() {
	*x = ListConsumerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConsumerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumerReply) ProtoMessage() {}

func (x *ListConsumerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumerReply.ProtoReflect.Descriptor instead.
func (*ListConsumerReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{9}
}

type CallProviderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CallProviderReply) Reset() {
	*x = CallProviderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallProviderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallProviderReply) ProtoMessage() {}

func (x *CallProviderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallProviderReply.ProtoReflect.Descriptor instead.
func (*CallProviderReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{10}
}

func (x *CallProviderReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CallProviderReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CallProviderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CallProviderReq) Reset() {
	*x = CallProviderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallProviderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallProviderReq) ProtoMessage() {}

func (x *CallProviderReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_service_v1_consumer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallProviderReq.ProtoReflect.Descriptor instead.
func (*CallProviderReq) Descriptor() ([]byte, []int) {
	return file_api_consumer_service_v1_consumer_proto_rawDescGZIP(), []int{11}
}

func (x *CallProviderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_consumer_service_v1_consumer_proto protoreflect.FileDescriptor

var file_api_consumer_service_v1_consumer_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x15,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x13,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x37, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x0f,
	0x43, 0x61, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32,
	0xfd, 0x04, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x6a, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x2a,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6a, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x6a, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x61, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12,
	0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x64, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x2a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x64, 0x0a, 0x0c, 0x43, 0x61, 0x6c,
	0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61,
	0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x42, 0x0a, 0x17, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x25, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_consumer_service_v1_consumer_proto_rawDescOnce sync.Once
	file_api_consumer_service_v1_consumer_proto_rawDescData = file_api_consumer_service_v1_consumer_proto_rawDesc
)

func file_api_consumer_service_v1_consumer_proto_rawDescGZIP() []byte {
	file_api_consumer_service_v1_consumer_proto_rawDescOnce.Do(func() {
		file_api_consumer_service_v1_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_consumer_service_v1_consumer_proto_rawDescData)
	})
	return file_api_consumer_service_v1_consumer_proto_rawDescData
}

var file_api_consumer_service_v1_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_consumer_service_v1_consumer_proto_goTypes = []interface{}{
	(*CreateConsumerReq)(nil),   // 0: api.consumer.service.v1.CreateConsumerReq
	(*CreateConsumerReply)(nil), // 1: api.consumer.service.v1.CreateConsumerReply
	(*UpdateConsumerReq)(nil),   // 2: api.consumer.service.v1.UpdateConsumerReq
	(*UpdateConsumerReply)(nil), // 3: api.consumer.service.v1.UpdateConsumerReply
	(*DeleteConsumerReq)(nil),   // 4: api.consumer.service.v1.DeleteConsumerReq
	(*DeleteConsumerReply)(nil), // 5: api.consumer.service.v1.DeleteConsumerReply
	(*GetConsumerReq)(nil),      // 6: api.consumer.service.v1.GetConsumerReq
	(*GetConsumerReply)(nil),    // 7: api.consumer.service.v1.GetConsumerReply
	(*ListConsumerReq)(nil),     // 8: api.consumer.service.v1.ListConsumerReq
	(*ListConsumerReply)(nil),   // 9: api.consumer.service.v1.ListConsumerReply
	(*CallProviderReply)(nil),   // 10: api.consumer.service.v1.CallProviderReply
	(*CallProviderReq)(nil),     // 11: api.consumer.service.v1.CallProviderReq
}
var file_api_consumer_service_v1_consumer_proto_depIdxs = []int32{
	0,  // 0: api.consumer.service.v1.Consumer.CreateConsumer:input_type -> api.consumer.service.v1.CreateConsumerReq
	2,  // 1: api.consumer.service.v1.Consumer.UpdateConsumer:input_type -> api.consumer.service.v1.UpdateConsumerReq
	4,  // 2: api.consumer.service.v1.Consumer.DeleteConsumer:input_type -> api.consumer.service.v1.DeleteConsumerReq
	6,  // 3: api.consumer.service.v1.Consumer.GetConsumer:input_type -> api.consumer.service.v1.GetConsumerReq
	8,  // 4: api.consumer.service.v1.Consumer.ListConsumer:input_type -> api.consumer.service.v1.ListConsumerReq
	11, // 5: api.consumer.service.v1.Consumer.CallProvider:input_type -> api.consumer.service.v1.CallProviderReq
	1,  // 6: api.consumer.service.v1.Consumer.CreateConsumer:output_type -> api.consumer.service.v1.CreateConsumerReply
	3,  // 7: api.consumer.service.v1.Consumer.UpdateConsumer:output_type -> api.consumer.service.v1.UpdateConsumerReply
	5,  // 8: api.consumer.service.v1.Consumer.DeleteConsumer:output_type -> api.consumer.service.v1.DeleteConsumerReply
	7,  // 9: api.consumer.service.v1.Consumer.GetConsumer:output_type -> api.consumer.service.v1.GetConsumerReply
	9,  // 10: api.consumer.service.v1.Consumer.ListConsumer:output_type -> api.consumer.service.v1.ListConsumerReply
	10, // 11: api.consumer.service.v1.Consumer.CallProvider:output_type -> api.consumer.service.v1.CallProviderReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_consumer_service_v1_consumer_proto_init() }
func file_api_consumer_service_v1_consumer_proto_init() {
	if File_api_consumer_service_v1_consumer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_consumer_service_v1_consumer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateConsumerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateConsumerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConsumerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConsumerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteConsumerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteConsumerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConsumerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConsumerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallProviderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_consumer_service_v1_consumer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallProviderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_consumer_service_v1_consumer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_consumer_service_v1_consumer_proto_goTypes,
		DependencyIndexes: file_api_consumer_service_v1_consumer_proto_depIdxs,
		MessageInfos:      file_api_consumer_service_v1_consumer_proto_msgTypes,
	}.Build()
	File_api_consumer_service_v1_consumer_proto = out.File
	file_api_consumer_service_v1_consumer_proto_rawDesc = nil
	file_api_consumer_service_v1_consumer_proto_goTypes = nil
	file_api_consumer_service_v1_consumer_proto_depIdxs = nil
}
